#include <stdlib.h>
#include <stdio.h>
#include <ncurses.h>
#include <string.h>
#include <pcap/pcap.h>
#include <netinet/tcp.h>
#include <netinet/udp.h>
#include <netinet/ip_icmp.h>
#include <signal.h>